// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as InputTxt from "./input.txt";

var input = InputTxt.default;

console.log(input);

var solutionPartOne = 0;

var solutionPartTwo = 0;

export {
  input ,
  solutionPartOne ,
  solutionPartTwo ,
  
}
/* input Not a pure module */
